branches:
  only:
    - master
    - develop
    - op-26
notifications:
  email:
    recipients:
        - kamil.swiader@hotmail.com
    on_success: never # default: change
    on_failure: always # default: always


  - language: node_js
        node_js: stable
        before_install:
          - cd frontend
        install:
          - npm install
        script:
          - npm run test
        after_script:
          - cd ..
