matrix:
 include:
  - language:
        node_js:
        - stable
        before_install:
          - cd frontend
        install:
          - npm install
        script:
          - npm run test
  - language: java
    jdk:
      - oraclejdk8
    before_install:
      - cd backend
    install:
      - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
    script:
      - mvn test
branches:
  only:
    - master
    - develop
    - op-26
notifications:
  email:
    recipients:
        - kamil.swiader@hotmail.com
    on_success: never # default: change
    on_failure: always # default: always