language: node_js
node_js:
  - "8"
dist: trusty
sudo: false

cache:
  directories:
    - node_modules

script:
  - npm run build

branches:
  only:
    - master
    - develop
    - op-26
notifications:
  email:
      recipients:
              - kamil.swiader@hotmail.com
      on_success: never # default: change
      on_failure: always # default: always