language: java
jdk:
  - oraclejdk8
  - oraclejdk10
  - oraclejdk-ea
  - openjdk10
  - openjdk11
before_script: cd backend
branches:
  only:
    - master
    - develop
    - op-26
notifications:
  email:
      recipients:
              - kamil.swiader@hotmail.com
              - tomaszwozniak96@gmail.com
      on_success: never # default: change
      on_failure: always # default: always