version: '3.5'

services:
  mysql:
    container_name: 'mysql'
    image: mysql/mysql-server:8.0.11
    ports:
      - 3336:3306
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: 'bank'
      MYSQL_USER: 'hr'
      MYSQL_PASSWORD: 'hr'

  backend:
    container_name: 'backend'
    image: 'backend'
    links:
      - mysql
      - kafka

  frontend:
    container_name: 'frontend'
    image: 'frontend'
    ports:
      - 4200:4200
      - 8080:4200
    links:
      - backend

  zookeeper:
    container_name: 'zookeeper'
    image: 'wurstmeister/zookeeper'
    ports:
      - 2181

  kafka:
    container_name: 'kafka'
    image: 'wurstmeister/kafka'
    build: .
    ports:
      - 9092
    environment:
      KAFKA_BROKER_ID: 0
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ZOOKEEPER_CONNECTION_TIMEOUT: 6000
      KAFKA_CREATE_TOPICS: "make-transfer:1:1,status-sender:1:1"
    links:
      - zookeeper
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

# sudo systemctl stop docker
# sudo dockerd -H tcp://0.0.0.0:2375 -H unix:///var/run/docker.sock